### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by DanielAndreasen**
## DO NOT MERGE YET

This PR is directly related to issue #35.

Note that this is yet to be tested, and should not be merged yet. It also still leaves a lot to be desired, but it's a first step towards cleaner code.

### CODE REVIEW

**Comment by J35P312** [comment]
Thanks a lot!
This looks like a great step forward!
I will start testing it tomorrow

**Comment by DanielAndreasen** [comment]
Sounds great. I think I will have some time tomorrow as well. Great talk today. You are a really good speaker :1st_place_medal:

**Comment by DanielAndreasen** [comment]
I have now made some small tests, and found some small bugs along the way, which I've fixed. Currently I am not sure `export` is working as intended, since this is not something we use.
Be sure to pull the latests commits from today, before testing.

**Comment by J35P312** [comment]
That's great!
I have done some tests, merging two files, building, querying, exporting small databases etc, using the latest commit.

To me it looks good! nothing crashes, and the result looks nice.

I will run a bigger test on a bigger dataset, it should be finished until monday (depending on queues on the server).
I will keep you updated, thanks for taking your time!
//Jesper

**Comment by J35P312** [comment]
Hello again!
Now I have tested databases of various size (up to 900 individuals), exporting and using the sqlite query. Everything works perfectly! I will merge this now, and start working on unit tests next week.

Thanks, and have a nice weekend!
//Jesper

**Comment by DanielAndreasen** [comment]
Hi Jesper, thanks for your testing. I will try to make smaller PRs from here with some refactoring. I think a vcf class could be handy.
Have a nice weekend

**Pull request merged**
