### PR TITLE
Fixed python import issue with python3

### PR DESCRIPTION
**Pull request by insung3511**
I got a issue in my raspberry pi and I little bit changed that import stuff like this
```
from . import [any module]
->
import [any module]
```

### CODE REVIEW

**Comment by insung3511** [comment]
Tbh Im not sure that I did well just trying to make it run. Its that have to use docker?

**Comment by DanielAndreasen** [comment]
Maybe have a look at the install instructions: https://github.com/J35P312/SVDB#install

**Comment by insung3511** [comment]
Hmm okay thanks. I will try it.

**Comment by J35P312** [comment]
Hello!
And thanks for contributing!
Bioinformatics on raspberry pi seems very cool =P.

There seems to be some import errors in the tests for py27 and py3, can you have a look; I would be happy to merge if this is resolved!

Do you get any issues running SVDB on raspberry pi? If so, feel free to make an issue!
best regards
Jesper

**Comment by insung3511** [comment]
Aight, thanks. Always trying to be helped 👍

**Pull request closed without merging**
